pool:
  # vmImage: 'vs2017-win2016'
  vmImage: 'win1803'

steps:
- script: |
    echo "about to login"
    echo $AUTH | docker login -u iain2 --password-stdin
    echo "about to build"
    docker build -f Dockerfile -t registry.gitlab.com/iain2/containerz .
    echo "about to push"
    docker push registry.gitlab.com/iain2/containerz
    echo "finished push"
  env:
    AUTH: $(auth)

