pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    docker login -u iain2 -p $LOGIN_INFO registry.gitlab.com
    docker build -f Dockerfile -t registry.gitlab.com/iain2/containerz .
    docker push registry.gitlab.com/iain2/containerz
  env:
    LOGIN_INFO: $(logininfo)

