pool:
  # vmImage: 'vs2017-win2016'
  vmImage: 'win1803'

steps:
- script: |
    docker login -u iain2 -p $AUTH registry.gitlab.com
    docker build -f Dockerfile -t registry.gitlab.com/iain2/containerz .
    docker push registry.gitlab.com/iain2/containerz
  env:
    AUTH: $(auth)

