pool:
  # vmImage: 'vs2017-win2016'
  vmImage: 'win1803'

steps:
- powershell: |
    echo "about to login"
    # echo $AUTH | docker login -u iain2 --password-stdin
    echo "AUTH: $AUTH. $env:AUTH"
    docker login -u iain2 -p "$AUTH"
    
    echo "about to build"
    docker build -f Dockerfile -t registry.gitlab.com/iain2/containerz:nanohello .
    
    echo "about to push"
    docker push registry.gitlab.com/iain2/containerz:nanohello
    
    echo "yaml pipeline done"
  env:
    AUTH: $(auth)

