pool:
  # vmImage: 'ubuntu-16.04'
  vmImage: 'vs2017-win2016'
  # vmImage: 'win1803'

steps:
- powershell: |
    echo "about to build"
    docker build -f Dockerfile -t registry.gitlab.com/iain2/containerz:nanohello .

    #echo "about to login"
    ## echo $env:AUTH | docker login -u iain2 --password-stdin registry.gitlab.com
    #docker login -u iain2 -p $env:AUTH registry.gitlab.com    
    
    #echo "about to push"
    #docker push registry.gitlab.com/iain2/containerz:nanohello
    
    echo "about to run"
    docker run registry.gitlab.com/iain2/containerz:nanohello
    
    echo "yaml pipeline done"
  env:
    AUTH: $(auth)

